### ISSUE TITLE
Hooking on to the session timeout

### ISSUE THREAD

**Issue by chriso86** [lindleycb/meteor-stale-session#14]
Hi guys,

I love the package, it is really simple to use and lightweight.

Just one thing that I have been unable to do, is hook on to the timer interval being set at startup.
I would like to add a notification countdown modal to display time left until automatic log out, however we are overwriting the Meteor.logout() method and I had hoped that Stale Session was using it but unfortunately that approach has failed.

Is there any way to latch on to Stale Session to create such a countdown display (ie. "30 seconds left")

Thank you and kind regards,
Chris

**Comment by AdamBrodzinski** [comment]
@chriso86 the easiest solution is to use a jquery plugin that will drop down a banner when you're about to log out. It has a config for timeouts and a callback on expiration which I used to logout from the client. It's not exact but close enough for me.  (you could even copy/paste the logic here if you want to build your own alert).

**Comment by sferoze** [comment]
@chriso86 I am trying to figure this out too and I don't quite understand @AdamBrodzinski method. Were you able to achieve this?

**Comment by chriso86** [comment]
@sferoze I was able to get a solution together for this problem using the sweet alert package for meteor, although it was not the most elegant solution.

Firstly, I built my solution into the client-side and server-side Meteor.startup methods.
I created a boolean flag in the server-side code to act as a warning indicator, then created a method to return it's value to a client-side call (which I had to implement my own interval to keep track of the flag status, and start the timeout counter if necessary).
I also added an interval to the server-side to monitor the heartbeat and set the flag.

This is my implementation, there is a bug that I know of where the popup is sporadic but I haven't had much time to debug it properly, this should not happen very often at all though since the conditions for it to occur are quite specific.
It does however work in a stable enough way for me.

@AdamBrodzinski Adam, I apologize for not responding as I was on a time constraint I had to find my own quick and dirty implementation for this - please advise @sferoze as to whether this is a viable solution as it does alter the source code.

Here is my implementation:

Server-side code:
```javascript
// Timeout variables
  var staleSessionPurgeInterval = Meteor.settings && Meteor.settings.public && Meteor.settings.public.staleSessionPurgeInterval || 1000; // 1 sec
  var inactivityTimeout = Meteor.settings && Meteor.settings.public && Meteor.settings.public.staleSessionInactivityTimeout || (3*60*1000); // 3 mins
  var warningInterval = Meteor.settings && Meteor.settings.public && Meteor.settings.public.staleSessionWarningInterval || (60*1000); // 1 min
  var heartbeat, warningIndicator = false;

  // Set heartbeat
  Meteor.methods({
    heartbeat: function(options) {
      if (!this.userId) { return; }
      var user = Meteor.users.findOne(this.userId);
      if (user) {
        heartbeat = new Date();
        Meteor.users.update(user._id, {$set: {heartbeat: heartbeat}});
      }
    },
    getWarningIndicator: function() {
      return warningIndicator;
    }
  });

  // Purge stale sessions
  Meteor.setInterval(function() {
    var now = new Date();
    var overdueTimestamp = new Date(now-inactivityTimeout);
    var warningTimestamp = now - (inactivityTimeout - warningInterval);

    // check if it is time to start the pop up warning
    if(heartbeat) {
      warningIndicator = heartbeat < warningTimestamp;
    } else {
      warningIndicator = false;
    }

    if(warningIndicator) {
      heartbeat = null;
    }

    Meteor.users.update({heartbeat: {$lt: overdueTimestamp}},
        {$set: {'services.resume.loginTokens': []},
          $unset: {heartbeat:1}},
        {multi: true});
  }, staleSessionPurgeInterval);
```

Client-side code:
```javascript
var heartbeatInterval = Meteor.settings && Meteor.settings.public && Meteor.settings.public.staleSessionHeartbeatInterval || (3*60*1000); // 3mins
  var activityEvents = Meteor.settings && Meteor.settings.public && Meteor.settings.public.staleSessionActivityEvents || 'click keydown';

  var activityDetected = false;
  var timerStarted     = false;

// Check when to turn timer on
  Meteor.setInterval(function () {
    Meteor.call("getWarningIndicator", function (error, result) {
      if (result && !timerStarted && Meteor.userId()) {
        startTimer();
      }
    });
  }, 500);

  var startTimer = function () {
    var warningInterval = Meteor.settings
        && Meteor.settings.public
        && Meteor.settings.public.staleSessionWarningInterval || (60*1000); // 1 min
    var count           = (warningInterval / 1000);
    timerStarted        = true;

    swal({
      title             : count,
      text              : " SECONDS REMAINING \nUNTIL AUTOMATIC LOGOUT",
      type              : "warning",
      showCancelButton  : false,
      confirmButtonClass: "warning",
      confirmButtonText : "Continue",
      allowOutsideClick : false
    }, function (onConfirm) {
      if (onConfirm) {
        if (countDown) {
          Meteor.clearInterval(countDown);
          timerStarted = false;
        }
      }
    });

    var countDown = Meteor.setInterval(function () {
      count -= 1;
      $('.sweet-alert>h2').text(count);
      // if counter reaches zero then close up and clean out
      if (count == 0) {
        swal.close();
        if (Meteor.userId()) Meteor.logout();
        Router.go('/');
        Meteor.clearInterval(countDown);
        timerStarted = false;
      }
    }, 1000);
  };

  // Send heartbeat if activity is detected//
  Meteor.setInterval(function () {
    if (Meteor.userId()) {
      if (activityDetected) {
        Meteor.call('heartbeat');
        activityDetected = false;
      }
    }
  }, heartbeatInterval);

// Read user activity//
  $(document).on(activityEvents, function () {
    activityDetected = true;
  });
```
